import React, { useRef } from 'react';
import { Button } from "@/components/ui/button";
import { FileText, Image as ImageIcon } from "lucide-react";
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { toast } from "sonner";

interface SummaryExportActionsProps {
  summaryText: string;
  title?: string;
  onExportComplete?: (url: string, type: "pdf" | "image") => void;
}

const SummaryExportActions = ({ 
  summaryText, 
  title = "Summary Report",
  onExportComplete 
}: SummaryExportActionsProps) => {
  const exportRef = useRef<HTMLDivElement>(null);

  // Export as PDF
  const exportToPDF = () => {
    try {
      const doc = new jsPDF();
      const splitText = doc.splitTextToSize(summaryText, 180);
      doc.setFontSize(16);
      doc.text(title, 10, 20);
      doc.setFontSize(12);
      doc.text(splitText, 10, 30);
      
      const fileName = `${title.toLowerCase().replace(/\s+/g, '-')}.pdf`;
      doc.save(fileName);
      
      // Create blob URL for callback
      const pdfBlob = doc.output('blob');
      const blobUrl = URL.createObjectURL(pdfBlob);
      onExportComplete?.(blobUrl, "pdf");
      
      toast.success("PDF downloaded successfully!");
    } catch (error) {
      console.error("Error exporting PDF:", error);
      toast.error("Failed to export PDF");
    }
  };

  // Export as Image
  const exportToImage = async () => {
    if (exportRef.current) {
      try {
        const canvas = await html2canvas(exportRef.current, {
          backgroundColor: "#ffffff",
          scale: 2,
        });
        const image = canvas.toDataURL("image/png");
        const link = document.createElement("a");
        link.href = image;
        link.download = `${title.toLowerCase().replace(/\s+/g, '-')}.png`;
        link.click();
        
        onExportComplete?.(image, "image");
        toast.success("Image saved successfully!");
      } catch (error) {
        console.error("Error exporting image:", error);
        toast.error("Failed to save image");
      }
    }
  };

  if (!summaryText) return null;

  return (
    <div className="w-full space-y-4">
      {/* Hidden capture area for image export */}
      <div 
        ref={exportRef} 
        className="rounded-xl border border-border bg-card p-6 shadow-sm"
      >
        <h3 className="mb-4 text-xl font-semibold text-foreground">{title}</h3>
        <p className="whitespace-pre-wrap text-sm leading-relaxed text-muted-foreground">
          {summaryText}
        </p>
        <p className="mt-6 text-xs text-muted-foreground/60">
          Generated by MindLink AI
        </p>
      </div>

      {/* Export Buttons */}
      <div className="flex flex-wrap gap-3">
        <Button 
          variant="outline" 
          onClick={exportToPDF}
          className="gap-2"
        >
          <FileText className="h-4 w-4" />
          Download PDF
        </Button>
        <Button 
          variant="outline" 
          onClick={exportToImage}
          className="gap-2"
        >
          <ImageIcon className="h-4 w-4" />
          Save as Image
        </Button>
      </div>
    </div>
  );
};

export default SummaryExportActions;
